version: '3.3'

services:

  api:
      container_name: api
      build: .
      ports:
        - "5000:5000"
      env_file:
          - env/api.env
      depends_on:
          - postgres

  postgres:
      image: postgres
      restart: always
      container_name: postgres
      volumes:
          - /postgres-data:/var/lib/postgresql
      ports:
          - "5432:5432"
      environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=root
          - POSTGRES_DB=root

